### ISSUE TITLE
Whether ![logo](logo.jpg) should better be ![logo](MacGesture2-Publish/logo.jpg)

### ISSUE THREAD

**Issue by TheoBlake** [CodeFalling/hexo-asset-image#30]
Here just a small tips for README.md, when edit a blog in Markdown editor, the insert path for logo.jpg should be `![logo](MacGesture2-Publish/logo.jpg)` instead of `![logo](logo.jpg)`.

**Comment by Gongzq5** [comment]
Yeah, I think using `![logo](MacGesture2-Publish/logo.jpg)` should be better way. Many markdown editor can auto copy the pic into this kind of path (`$foldername$/logo.jpg`), so we can see pic in local markdown editor immediately. 

I make some change in source code so that it can support this kind of url.

In source code `node_modules\_hexo-asset-image@0.0.3@hexo-asset-image\index.js`, in line **34, 35** the `if` statement can be commented out to get this effect. After this change, some bug may will show(however I haven't met, at least it can be normally used in general **_post_** files.).

```js
34. // if(!/http[s]*.*|\/\/.*/.test(src) &&
35.   // !/^\s*\//.test(src)) {
```

Of course, the closing `}` should be commented too.
